name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: cboone/gh-actions/.github/workflows/go-ci.yml@v2.1.2
    with:
      run-scrut: true
      scrut-build-cmd: "go build ."
