name: gitleaks

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  gitleaks:
    uses: cboone/gh-actions/.github/workflows/secret-scan.yml@main
    with:
      tool: gitleaks
